/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RemoteIndexImport } from './routes/remote/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RemoteIndexRoute = RemoteIndexImport.update({
  id: '/remote/',
  path: '/remote/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/remote/': {
      id: '/remote/'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/remote': typeof RemoteIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/remote': typeof RemoteIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/remote/': typeof RemoteIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/remote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/remote'
  id: '__root__' | '/' | '/remote/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RemoteIndexRoute: typeof RemoteIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RemoteIndexRoute: RemoteIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/remote/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/remote/": {
      "filePath": "remote/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
