/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ButtonsIndexImport } from './routes/buttons/index'
import { Route as AboutIndexImport } from './routes/about/index'

// Create/Update Routes

const ButtonsIndexRoute = ButtonsIndexImport.update({
  id: '/buttons/',
  path: '/buttons/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/buttons/': {
      id: '/buttons/'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutIndexRoute
  '/buttons': typeof ButtonsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutIndexRoute
  '/buttons': typeof ButtonsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about/': typeof AboutIndexRoute
  '/buttons/': typeof ButtonsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/buttons'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/buttons'
  id: '__root__' | '/about/' | '/buttons/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
  ButtonsIndexRoute: typeof ButtonsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
  ButtonsIndexRoute: ButtonsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about/",
        "/buttons/"
      ]
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/buttons/": {
      "filePath": "buttons/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
